name: Build Docker Image, Push to GHCR

on:
  push:
    # Publish HEAD of main branch as :latest image tag
    branches: [ "main", "ohm" ]
    # Publish semver tags as named image tags
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: opnhistoricalmap/osmcha-frontend
  REACT_APP_PAGE_SIZE: "25"
  REACT_APP_OVERPASS_BASE: "//overpass-api.openhistoricalmap.org/api/interpreter"
  REACT_APP_MAPBOX_ACCESS_TOKEN: "pk.eyJ1Ijoib3Blbmhpc3RvcmljYWxtYXAiLCJhIjoiY202a3ZqcHN1MDJnYzJpcHhlczVqbXBuNiJ9.DvNrZEF1ISEluA9k-MSHtA"
  REACT_APP_OSM_URL: "https://www.openhistoricalmap.org"
  REACT_APP_OSM_API: "https://api.openhistoricalmap.org/api/0.6"
  REACT_APP_NOMINATIM_URL: "https://nominatim-api.openhistoricalmap.org/search.php"
  REACT_APP_DEFAULT_FROM_DATE: "2"
  REACT_APP_DEFAULT_TO_DATE: "5"
  REACT_APP_DISABLE_REAL_CHANGESETS: "false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Enable BuildKit for docker builds. This enables building
    # multi-platform images and exporting the layer cache
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # https://github.com/docker/login-action
    - name: Login to Registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          REACT_APP_PAGE_SIZE=${{ env.REACT_APP_PAGE_SIZE }}
          REACT_APP_OVERPASS_BASE=${{ env.REACT_APP_OVERPASS_BASE }}
          REACT_APP_MAPBOX_ACCESS_TOKEN=${{ env.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_OSM_URL=${{ env.REACT_APP_OSM_URL }}
          REACT_APP_OSM_API=${{ env.REACT_APP_OSM_API }}
          REACT_APP_NOMINATIM_URL=${{ env.REACT_APP_NOMINATIM_URL }}
          REACT_APP_DEFAULT_FROM_DATE=${{ env.REACT_APP_DEFAULT_FROM_DATE }}
          REACT_APP_DEFAULT_TO_DATE=${{ env.REACT_APP_DEFAULT_TO_DATE }}
          REACT_APP_DISABLE_REAL_CHANGESETS=${{ env.REACT_APP_DISABLE_REAL_CHANGESETS }}
          